sudo: false
language: python
services:
  - memcached
  - postgresql
  - redis-server
python:
  - "2.7"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
install:
    - pip install -U pip setuptools wheel codecov
    - pip install psycopg2==2.7.0
    - pip install .
script:
  - flake8
  - py.test